name: Playwright Test Bot

on:
  workflow_dispatch:  # هذا يضيف زر تشغيل يدوي
  push:
    branches: [ main ]
  schedule:
    - cron: '*/30 * * * *'  # اختياري، للتشغيل الدوري

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run Playwright script
        run: python main.py
